# Enginered by: Avinash Kumar<avinash.kumar@hashedin.com> & Satya Kumar <satya.kumar@hashedin.com>
# image: docker:latest
# services:
#   - docker:dind

stages:
  # - build_dialogflow
  - cloud_deploy

# cache:
#     paths:
#     - ./node_modules

# generate_artifact:
#  image: node:14-alpine
#  stage: build_dialogflow
#  only:
#  - master
#  script:
#   - npm install
#  artifacts:
#   paths:
#     - ./node_modules

gcloud_deploy:
  image: google/cloud-sdk:alpine
  stage: cloud_deploy
  environment: staging
  only:
  - master
  before_script:
  - "echo ${GITLAB_USER_LOGIN/./-}"
  - Servicename='askharshachatbot'
  - "echo $Servicename"
  - ServiceName=${Servicename//-}
  - echo $ServiceName
  - "echo $CI_PROJECT_NAME"
  - "cat app.yaml"
  - echo $SERVICE_ACCOUNT > ${CI_PIPELINE_ID}.json

  
  script:
  - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
  - gcloud --project hu18-groupa-angular app deploy --version v1 --appyaml app.yaml
  - url=$(gcloud app services browse $ServiceName --no-launch-browser --project hu18-groupa-angular)
  - echo $url
  
  after_script:
  - rm $CI_PIPELINE_ID.json
